version: '3.8'

# ====================================
# Whisper-Insights - Docker Compose
# ====================================

services:
  # ====================================
  # Aplicação Principal
  # ====================================
  whisper-insights:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DEBIAN_FRONTEND=noninteractive
    image: whisper-insights:latest
    container_name: whisper-insights-app
    restart: unless-stopped

    # Configuração de rede
    ports:
      - "5001:5001"

    # Variáveis de ambiente
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - PYTHONUNBUFFERED=1
      - TZ=America/Sao_Paulo

    # Arquivo de environment
    env_file:
      - .env

    # Volumes persistentes
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - whisper_models:/root/.cache/whisper
      - huggingface_cache:/root/.cache/huggingface

    # Configuração de recursos
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 1G
          cpus: '1.0'

    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

    # Dependências
    # depends_on:
    #   - ollama

    # Configuração de logging
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

  # ====================================
  # Ollama (IA Local) - Opcional
  # ====================================
  ollama:
    image: ollama/ollama:latest
    container_name: whisper-insights-ollama
    restart: unless-stopped

    # Configuração de rede
    ports:
      - "11434:11434"

    # Variáveis de ambiente
    environment:
      - OLLAMA_HOST=0.0.0.0

    # Volumes para modelos
    volumes:
      - ollama_data:/root/.ollama

    # GPU support (opcional - descomente se tiver GPU)
    # runtime: nvidia
    # environment:
    #   - NVIDIA_VISIBLE_DEVICES=all
    #   - NVIDIA_DRIVER_CAPABILITIES=compute,utility

    # Configuração de recursos
    deploy:
      resources:
        limits:
          memory: 8G
          cpus: '4.0'
        reservations:
          memory: 2G
          cpus: '1.0'

    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

    # Configuração de logging
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  # ====================================
  # Nginx (Reverse Proxy) - Opcional
  # ====================================
  nginx:
    image: nginx:alpine
    container_name: whisper-insights-nginx
    restart: unless-stopped

    # Configuração de rede
    ports:
      - "80:80"
      - "443:443"

    # Volumes de configuração
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/ssl:/etc/nginx/ssl:ro

    # Dependências
    depends_on:
      - whisper-insights

    # Configuração de logging
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

    # Configuração condicional (desabilitado por padrão)
    profiles:
      - production

# ====================================
# Volumes Nomeados
# ====================================
volumes:
  # Cache de modelos Whisper
  whisper_models:
    driver: local

  # Cache Hugging Face (para diarização)
  huggingface_cache:
    driver: local

  # Dados do Ollama
  ollama_data:
    driver: local

# ====================================
# Redes
# ====================================
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16